<?xml version="1.0"?>
<robot name="arv" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="LIDAR" params="base_link">
    <xacro:property name="lidar_base_link"		value="${base_link}"/>
    <xacro:property name="lidar_origin_rpy"		value="0 0 0"/>
    <xacro:property name="lidar_origin_xyz"		value="${hingeX} 0 ${chassisHeight/2.0+0.05}"/>
    <xacro:property name="lidar_height"		value="0.0717"/>
    <xacro:property name="lidar_radius"		value="0.0516"/>
    <xacro:property name="lidar_mass"		value="0.15"/>

    <xacro:property name="lidar_update_rate"		value="400"/>
    <xacro:property name="lidar_link"  			value="lidar_link"/>
    <xacro:property name="lidar_topic" 			value="/scan"/>

    <joint name="lidar_joint" type="fixed">
      <origin xyz="${lidar_origin_xyz}" rpy="${lidar_origin_rpy}"/>
      <parent link="${lidar_base_link}"/>
      <child link="lidar_link"/>
    </joint>

    <link name="lidar_link">
      <inertial>
        <mass value="${lidar_mass}"/>
        <origin xyz="0 0 0"/>
        <xacro:cylinder_inertia m="${lidar_mass}" r="${lidar_radius}" h="${lidar_height}"/>
      </inertial>
      <visual>
        <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
        </geometry>
      </collision>
    </link>

    <gazebo reference="lidar_link">
      <sensor name='gpu_lidar' type='gpu_lidar'>
          <topic>${lidar_topic}</topic>
          <update_rate>${lidar_update_rate}</update_rate>
          <ignition_frame_id>arv/lidar_link</ignition_frame_id>
          <lidar>
              <scan>
                  <horizontal>
                      <samples>640</samples>
                      <resolution>1</resolution>
                      <min_angle>-1.396263</min_angle>
                      <max_angle>1.396263</max_angle>
                  </horizontal>
                <vertical>
                  <samples>1</samples>
                  <resolution>1</resolution>
                  <min_angle>0.0</min_angle>
                  <max_angle>0.0</max_angle>
                </vertical>
              </scan>
              <range>
                  <min>0.08</min>
                  <max>10</max>
                  <resolution>0.01</resolution>
              </range>
              <noise>
                  <type>gaussian</type>
                  <mean>0.0</mean>
                  <stddev>0.001</stddev>
              </noise>
          </lidar>
          <alwaysOn>1</alwaysOn>
          <visualize>true</visualize>
        </sensor>
      </gazebo>

      <gazebo reference="lidar_joint">
        <preserveFixedJoint>true</preserveFixedJoint>
      </gazebo>

  </xacro:macro>

</robot>
