<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="hinge" params="prefix X Y">
        <joint name="${prefix}_HINGE_JOINT" type="revolute">
            <parent link="${base_link_name}"/>
            <child link="${prefix}_HINGE"/>
            <origin xyz="${X} ${Y} ${wheelHeight - chassisHeight/2.0}" rpy="-${0.5*PI} 0.0 0.0"/>
            <axis xyz="0 -1 0" rpy="0 0 0"/>
            <dynamics damping="0.0" friction="0.0"/>
            <limit lower="-0.53" upper="0.53" effort="100.0" velocity="5.0"/>
        </joint>

        <link name="${prefix}_HINGE">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${hingeRadius}" length="${hingeLength}"/>
                </geometry>
            </visual>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="${hingeMass}"/>
                <xacro:cylinder_inertia m="${hingeMass}" r="${hingeRadius}" h="${hingeLength}"/>
            </inertial>
        </link>

    </xacro:macro>

</robot>