<?xml version="1.0"?>

<!-- This file contains plugins to simulate an Imu sensor attached to the robot. -->
<!-- Documentation can be found at http://wiki.ros.org/hector_gazebo_plugins -->

<robot name="arv" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="IMU" params="base_link">
    <!--                              Imu  Properties 				          	-->
    <xacro:property name="imu_base_link"		value="${base_link}"/>
    <xacro:property name="imu_origin_rpy"		value="0 0 0"/>
    <xacro:property name="imu_origin_xyz"		value="-0.2159 -0.02397 ${chassisHeight/2.0+0.005}"/>

    <xacro:property name="imu_update_rate"		value="400"/>
    <xacro:property name="imu_link"  			value="imu_link"/>
    <xacro:property name="imu_topic" 			value="/imu0"/>
    <xacro:property name="imu_calibration_service_name" value="/imu/calibrate"/>
    <xacro:property name="acceleration_offset"          value="0.0 0.0 0.0"/>
    <xacro:property name="acceleration_drift"           value="0.0 0.0 0.0"/>
    <xacro:property name="acceleration_drift_frequency" value="0.0 0.0 0.0"/>
    <xacro:property name="acceleration_gaussian_noise" 	value="0.0 0.0 0.0"/>
    <xacro:property name="rate_offset" 			value="0.0 0.0 0.0"/>
    <xacro:property name="rate_drift" 			value="0.0 0.0 0.0"/>
    <xacro:property name="rate_drift_frequency"	 	value="0.0 0.0 0.0"/>
    <xacro:property name="rate_gaussian_noise" 		value="0.0 0.0 0.0"/>
    <xacro:property name="heading_offset" 		value="0.0"/>
    <xacro:property name="heading_drift" 		value="0.0"/>
    <xacro:property name="heading_drift_frequency" 	value="0.0"/>
    <xacro:property name="heading_gaussian_noise" 	value="0.0"/>

    <gazebo reference="imu_link">
        <gravity>true</gravity>
        <sensor name="imu_sensor" type="imu">
            <always_on>true</always_on>
            <update_rate>${imu_update_rate}</update_rate>
            <visualize>true</visualize>
            <topic>__default_topic__</topic>
            <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
                <topicName>imu</topicName>
                <bodyName>${imu_link}</bodyName>
                <updateRateHZ>10.0</updateRateHZ>
                <gaussianNoise>0.0</gaussianNoise>
                <xyzOffset>0 0 0</xyzOffset>
                <rpyOffset>0 0 0</rpyOffset>
                <frameName>${imu_link}</frameName>
                <initialOrientationAsReference>false</initialOrientationAsReference>
            </plugin>
            <pose>0 0 0 0 0 0</pose>
        </sensor>
    </gazebo>

    <!-- Imu is fixed to the base link -->
    <joint name="imu_joint" type="fixed">
        <origin xyz="${imu_origin_xyz}" rpy="${imu_origin_rpy}"/>
        <parent link="${imu_base_link}"/>
        <child link="${imu_link}"/>
    </joint>

    <!-- Imu link -->
    <link name="${imu_link}">
        <inertial>
            <mass value="0.001"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.04 0.05 0.02"/>
            </geometry>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size=".001 .001 .001"/>
            </geometry>
        </collision>
        <!--
        <material name="orange">
            <color rgba="255 108 10 255"/>
        </material>
        -->
    </link>

    <gazebo reference="${imu_link}">
        <material>Gazebo/Orange</material>
    </gazebo>


    <gazebo reference="imu_joint">
        <preserveFixedJoint>true</preserveFixedJoint>
    </gazebo>

  </xacro:macro> 
</robot> 
