<?xml version="1.0"?>
<robot name="arv" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="simulation"   		default="true"/>
  <xacro:arg name="gpu" 		 		default="false"/>
  <xacro:arg name="pointcloud_topic"	default="/rslidar_points"/>

  <xacro:property name="gpu" 		value="$(arg gpu)" />

  <xacro:macro name="LIDAR" params="base_link">

    <xacro:include filename="$(find arv_description)/urdf/VLP-16.urdf.xacro"/>

    <xacro:VLP-16 parent="${base_link}" name="rslidar" topic="$(arg pointcloud_topic)" hz="10" samples="440" gpu="${gpu}">
      <origin xyz="0.2159 0 ${chassisHeight/2.0+0.05}" rpy="0 0 0" />
    </xacro:VLP-16>

    <gazebo reference="rslidar_base_mount_joint">
      <preserveFixedJoint>true</preserveFixedJoint>
    </gazebo>

    <gazebo reference="rslidar_base_scan_joint">
      <preserveFixedJoint>true</preserveFixedJoint>
    </gazebo>

  </xacro:macro>

</robot>
